DROP DATABASE IF EXISTS todo_list;
CREATE DATABASE todo_list;
USE todo_list;

DROP TABLE IF EXISTS tasks;
CREATE TABLE tasks (
	ID INT AUTO_INCREMENT,
    Title VARCHAR(255),
    Description TEXT,
    Completed TINYINT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_tasks PRIMARY KEY (id)
)